services:
  - type: web
    name: GDSC
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Blog.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blog.settings
