# Generated by Django 5.2.5 on 2025-08-18 18:31

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images/%y', validators=[main.validators.validate_image_extension, main.validators.file_limit]),
        ),
    ]
