# Generated by Django 5.2.5 on 2025-08-18 18:32

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='images/%y', validators=[main.validators.validate_image_extension, main.validators.file_limit]),
        ),
    ]
