# Generated by Django 5.2.5 on 2025-08-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blogmodel_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='thumbnail',
        ),
    ]
