# Generated by Django 5.2.5 on 2025-08-18 18:36

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_blogmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='thumbnails/%y', validators=[main.validators.validate_image_extension, main.validators.file_limit]),
        ),
    ]
