# Generated by Django 5.2.5 on 2025-08-23 08:45

import django.db.models.deletion
import django_resized.forms
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blogmodel_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[232, 216], upload_to='thumbnails/%y', validators=[main.validators.validate_image_extension, main.validators.file_limit]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blogmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
