# Generated by Django 5.2.5 on 2025-08-23 08:53

import django_resized.forms
import main.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blogmodel_thumbnail_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[232, 216], upload_to='thumbnails/%y', validators=[main.validators.validate_image_extension, main.validators.file_limit]),
        ),
    ]
