# Generated by Django 5.2.5 on 2025-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_categorymodel_tagsmodel_blogmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='TagsModel',
        ),
    ]
