# Generated by Django 5.2.5 on 2025-09-04 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_blogmodel_category_remove_blogmodel_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='was_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='when_last_updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
