# Generated by Django 5.2.5 on 2025-09-04 15:37

import django_resized.forms
import main.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_blogmodel_was_updated_blogmodel_when_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[232, 216], upload_to='thumbnails/%y', validators=[main.validators.validate_image_extension, main.validators.file_limit]),
        ),
    ]
