# Generated by Django 5.2.5 on 2025-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_blogmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='when_last_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
