# Generated by Django 5.2.5 on 2025-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_profile_facebook_profile_inst_profile_twitter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
